# Generated by Django 5.2.7 on 2025-11-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReeferBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
                ('numero_economico', models.CharField(max_length=20, unique=True, verbose_name='Número económico')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de serie')),
                ('placas', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Placas')),
                ('km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kilometraje')),
                ('ciclo_mtto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciclo Mtto')),
                ('rin', models.CharField(blank=True, max_length=30, null=True, verbose_name='Rin')),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso bruto (kg)')),
                ('combustible', models.CharField(blank=True, max_length=30, null=True, verbose_name='Combustible')),
                ('capacidad_thermo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidad de Thermo (BTU o HP)')),
                ('tipo_remolque', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de remolque')),
                ('seguro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguro (póliza/folio)')),
                ('tarjeta_circulacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarjeta de circulación')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Caja refrigerada',
                'verbose_name_plural': 'Cajas refrigeradas',
                'ordering': ['numero_economico'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(max_length=15, unique=True, verbose_name='Placas')),
                ('numero_economico', models.CharField(max_length=20, unique=True, verbose_name='Número económico')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serie (VIN)')),
                ('marca', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca')),
                ('motor', models.CharField(blank=True, max_length=80, null=True, verbose_name='Motor')),
                ('combustible', models.CharField(blank=True, max_length=30, null=True, verbose_name='Combustible')),
                ('capacidad_combustible', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Capacidad de combustible (L)')),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso bruto (kg)')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
                ('rin', models.CharField(blank=True, max_length=30, null=True, verbose_name='Rin')),
                ('ciclo_mtto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciclo Mtto')),
                ('seguro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguro (póliza/folio)')),
                ('tarjeta_circulacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarjeta de circulación')),
                ('iave', models.CharField(blank=True, max_length=100, null=True, verbose_name='IAVE')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Camión',
                'verbose_name_plural': 'Camiones',
                'ordering': ['numero_economico'],
            },
        ),
    ]
