# Generated by Django 5.2.7 on 2025-11-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reeferbox',
            name='nombre',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='nombre',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
