# Generated by Django 5.2.7 on 2025-11-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_reeferbox_nombre_truck_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='nombre',
        ),
    ]
