# Generated by Django 5.2.7 on 2026-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_remove_truck_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
    ]
