# Generated by Django 5.2.7 on 2026-01-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_truck_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reeferbox',
            name='nombre',
        ),
    ]
