# Generated by Django 5.2.7 on 2026-01-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], default='ALTA', max_length=10)),
                ('nombre', models.CharField(max_length=120)),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('calle', models.CharField(blank=True, max_length=120, null=True)),
                ('no_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('colonia_sat', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(blank=True, max_length=120, null=True)),
                ('pais', models.CharField(default='México', max_length=80)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['deleted'], name='suppliers_s_deleted_207493_idx'), models.Index(fields=['nombre'], name='suppliers_s_nombre_5cfa8d_idx')],
            },
        ),
    ]
