# Generated by Django 5.2.7 on 2025-10-20 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('rfc', models.CharField(help_text='Ej: ABCD010203XYZ', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$', message='RFC inválido')], verbose_name='RFC')),
                ('license_number', models.CharField(max_length=30, unique=True, verbose_name='No. de Licencia')),
                ('license_expires_at', models.DateField(verbose_name='Vigencia de licencia')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
