# Generated by Django 5.2.7 on 2025-10-21 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='last_name',
        ),
        migrations.AddField(
            model_name='operator',
            name='last_name_materno',
            field=models.CharField(blank=True, max_length=80, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='operator',
            name='last_name_paterno',
            field=models.CharField(default='', max_length=80, verbose_name='Apellido paterno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operator',
            name='first_name',
            field=models.CharField(max_length=80, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='rfc',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$', message='RFC inválido')], verbose_name='RFC'),
        ),
    ]
