# Generated by Django 5.2.7 on 2025-10-21 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_remove_operator_last_name_operator_last_name_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$', message='RFC inválido')], verbose_name='RFC'),
        ),
    ]
