# Generated by Django 5.2.7 on 2025-11-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_alter_operator_rfc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ['nombre'], 'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.RemoveField(
            model_name='operator',
            name='active',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='last_name_materno',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='last_name_paterno',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='license_expires_at',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='operator',
            name='antidoping',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='antidoping_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='calle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='colonia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='colonia_sat',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='cuenta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='estado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='examen_medico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='examen_medico_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='imss',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='ine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='ine_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='licencia_federal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='licencia_federal_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='municipio',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='no_ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='nombre',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='pais',
            field=models.CharField(default='MÉXICO', max_length=80),
        ),
        migrations.AddField(
            model_name='operator',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='pasaporte_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='periodicidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='poblacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='puesto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='rcontrol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='rcontrol_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='salario_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='status',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], default='ALTA', max_length=10),
        ),
        migrations.AddField(
            model_name='operator',
            name='sueldo_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('BASE', 'Base'), ('TEMPORAL', 'Temporal'), ('HONORARIOS', 'Honorarios')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='tipo_jornada',
            field=models.CharField(blank=True, choices=[('DIURNA', 'Diurna'), ('NOCTURNA', 'Nocturna'), ('MIXTA', 'Mixta')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='tipo_liquidacion',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='tipo_regimen',
            field=models.CharField(blank=True, choices=[('ASALARIADO', 'Asalariado'), ('INDEPENDIENTE', 'Independiente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='tope',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='visa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='visa_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='rfc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
