# Generated by Django 5.2.7 on 2025-11-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_alter_operator_options_remove_operator_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
