# Generated by Django 5.2.7 on 2025-11-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_operator_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='salario_diario',
        ),
    ]
