# Generated by Django 5.2.7 on 2025-11-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_remove_operator_salario_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='pais',
            field=models.CharField(default='México', max_length=80),
        ),
    ]
