# Generated by Django 5.2.7 on 2026-01-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_alter_operator_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='cross_border',
            field=models.CharField(choices=[('NO_PUEDE', 'No puede cruzar'), ('PUEDE', 'Puede cruzar'), ('SOLO_CRUCE', 'Solo cruce (transfer)')], default='NO_PUEDE', max_length=20, verbose_name='Cruce frontera (USA)'),
        ),

        
    ]
