# Generated by Django 5.2.7 on 2026-01-19 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_operator_cross_border'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
    ]
