# Generated by Django 5.2.7 on 2025-12-09 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0003_workshoporder_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit', models.CharField(default='pieza', help_text='Ej. pieza, litro, juego, etc.', max_length=20, verbose_name='Unidad de medida')),
                ('location', models.CharField(blank=True, help_text='Ej. Estante A, Nivel 2, Caja 3', max_length=100, verbose_name='Ubicación en almacén')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Alerta si el stock actual baja de este valor.', max_digits=10, verbose_name='Stock mínimo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Refacción',
                'verbose_name_plural': 'Refacciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SparePartPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Proveedor')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Factura / Folio')),
                ('date', models.DateField(verbose_name='Fecha de compra')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Compra de refacciones',
                'verbose_name_plural': 'Compras de refacciones',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePartPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='warehouse.sparepartpurchase', verbose_name='Compra')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='warehouse.sparepart', verbose_name='Refacción')),
            ],
            options={
                'verbose_name': 'Partida de compra',
                'verbose_name_plural': 'Partidas de compra',
            },
        ),
        migrations.CreateModel(
            name='SparePartMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INITIAL', 'Carga inicial'), ('PURCHASE', 'Compra'), ('WORKSHOP_USAGE', 'Consumo en orden de taller'), ('ADJUST_IN', 'Ajuste de entrada'), ('ADJUST_OUT', 'Ajuste de salida')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Útil para valuación de inventario.', max_digits=12, null=True, verbose_name='Costo unitario')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.sparepart', verbose_name='Refacción')),
                ('workshop_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_movements', to='workshop.workshoporder', verbose_name='Orden de taller')),
                ('purchase_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='warehouse.sparepartpurchaseitem', verbose_name='Partida de compra origen')),
            ],
            options={
                'verbose_name': 'Movimiento de refacción',
                'verbose_name_plural': 'Movimientos de refacciones',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
