# Generated by Django 5.2.7 on 2025-12-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='location',
        ),
    ]
