# Generated by Django 5.2.7 on 2026-01-14 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('warehouse', '0002_remove_sparepart_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepartpurchase',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='sparepartpurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Proveedor registrado en el catálogo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_part_purchases', to='suppliers.supplier', verbose_name='Proveedor'),
        ),
    ]
