# Generated by Django 5.2.7 on 2026-01-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_sparepartpurchase_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartpurchase',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada a aprobación'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estatus'),
        ),
    ]
