# Generated by Django 5.2.7 on 2026-01-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('warehouse', '0004_sparepartpurchase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de pago')),
                ('method', models.CharField(choices=[('TRANSFER', 'Transferencia'), ('CASH', 'Efectivo'), ('CHECK', 'Cheque'), ('CARD', 'Tarjeta'), ('OTHER', 'Otro')], default='TRANSFER', max_length=20, verbose_name='Método')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Referencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('status', models.CharField(choices=[('POSTED', 'Aplicado'), ('VOID', 'Anulado')], db_index=True, default='POSTED', max_length=20, verbose_name='Estatus')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Pago a proveedor',
                'verbose_name_plural': 'Pagos a proveedores',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto aplicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='warehouse.supplierpayment', verbose_name='Pago')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='warehouse.sparepartpurchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Aplicación de pago',
                'verbose_name_plural': 'Aplicaciones de pagos',
                'ordering': ['-id'],
            },
        ),
    ]
