# Generated by Django 5.2.7 on 2026-01-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('warehouse', '0005_supplierpayment_supplierpaymentallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='suppliers.supplier', verbose_name='Proveedor'),
        ),
    ]
