# Generated by Django 5.2.7 on 2026-02-10 23:48

import django.db.models.deletion
import django.utils.timezone
import settlement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0009_operator_user'),
        ('trips', '0021_remove_cartaportelocation_fecha_hora_salida_llegada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Lista (aprobada)'), ('paid', 'Pagada'), ('canceled', 'Cancelada')], default='draft', max_length=16)),
                ('unit_label', models.CharField(help_text='Ej. T06', max_length=32)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='operators.operator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorSettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ingreso', 'Ingreso'), ('anticipo', 'Anticipo / Descuento'), ('gasto', 'Gasto'), ('caseta', 'Caseta')], max_length=16)),
                ('concept', models.CharField(max_length=120)),
                ('payment_type', models.CharField(blank=True, default='', help_text='Ej. Efectivo, Depósito, Infonavit', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Siempre positivo; la categoría define si suma o resta.', max_digits=10)),
                ('notes', models.CharField(blank=True, default='', max_length=280)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='settlement.operatorsettlement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OperatorSettlementTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('load', 'Carga (ida)'), ('return', 'Baja (vuelta)')], default='load', max_length=16)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='settlement.operatorsettlement')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_memberships', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_settlement_approvals', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_settlement_approvals', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_approval', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('load', 'Foto de la carga'), ('seal', 'Foto del sello'), ('other', 'Otro')], default='other', max_length=24)),
                ('image', models.ImageField(upload_to=settlement.models.settlement_evidence_upload_path)),
                ('notes', models.CharField(blank=True, default='', max_length=280)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.CharField(blank=True, default='', max_length=280)),
                ('deleted', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_settlement_evidences', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_evidences', to='trips.trip')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_settlement_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='operatorsettlement',
            index=models.Index(fields=['status'], name='settlement__status_47d75a_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorsettlement',
            index=models.Index(fields=['operator', 'created_at'], name='settlement__operato_5892bc_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorsettlementline',
            index=models.Index(fields=['settlement', 'category'], name='settlement__settlem_c20e55_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorsettlementtrip',
            index=models.Index(fields=['settlement', 'role'], name='settlement__settlem_e4ba3e_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorsettlementtrip',
            index=models.Index(fields=['trip'], name='settlement__trip_id_37a7b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorsettlementtrip',
            unique_together={('settlement', 'role')},
        ),
        migrations.AddIndex(
            model_name='settlementapproval',
            index=models.Index(fields=['status'], name='settlement__status_83796e_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementevidence',
            index=models.Index(fields=['trip', 'evidence_type'], name='settlement__trip_id_6922ce_idx'),
        ),
        migrations.AddIndex(
            model_name='settlementevidence',
            index=models.Index(fields=['trip', 'deleted'], name='settlement__trip_id_db71ce_idx'),
        ),
    ]
