# Generated by Django 5.2.7 on 2026-01-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('fraccion_arancelaria', models.CharField(blank=True, db_index=True, help_text='Ej: 01012101 (se guarda como texto por posibles variantes/formato).', max_length=20, null=True, verbose_name='Fracción arancelaria')),
                ('comercio_exterior_uuid', models.UUIDField(blank=True, help_text='UUID asociado a comercio exterior (si aplica).', null=True, unique=True, verbose_name='UUID Comercio Exterior')),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Mercancía',
                'verbose_name_plural': 'Mercancías',
                'ordering': ['clave', 'nombre'],
                'indexes': [models.Index(fields=['deleted', 'clave'], name='goods_merca_deleted_d75bb6_idx'), models.Index(fields=['deleted', 'nombre'], name='goods_merca_deleted_4c2ffe_idx')],
            },
        ),
    ]
