# Generated by Django 5.2.7 on 2026-02-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='moneda',
            field=models.CharField(blank=True, default='MXN', max_length=3),
        ),
        migrations.AddField(
            model_name='mercancia',
            name='pedimento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mercancia',
            name='valor_mercancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
