# Generated by Django 5.2.7 on 2025-11-06 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], default='ALTA', max_length=10)),
                ('nombre', models.CharField(max_length=120)),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('rfc', models.CharField(blank=True, max_length=15, null=True)),
                ('regimen_fiscal', models.CharField(blank=True, choices=[('601', '601 - General de Ley Personas Morales'), ('603', '603 - Personas Morales con Fines no Lucrativos'), ('605', '605 - Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('612', '612 - Personas Físicas con Actividades Empresariales y Profesionales'), ('616', '616 - Sin obligaciones fiscales'), ('OTRO', 'Otro')], max_length=10, null=True)),
                ('id_tributario', models.CharField(blank=True, max_length=30, null=True)),
                ('calle', models.CharField(blank=True, max_length=120, null=True)),
                ('no_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=120, null=True)),
                ('colonia_sat', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(blank=True, max_length=120, null=True)),
                ('pais', models.CharField(default='México', max_length=80)),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('poblacion', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('dias_credito', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('forma_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('PPD', 'PPD - Pago en parcialidades o diferido'), ('PUE', 'PUE - Pago en una sola exhibición'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('uso_cfdi', models.CharField(blank=True, choices=[('G01', 'Adquisición de mercancías'), ('G03', 'Gastos en general'), ('I01', 'Construcciones'), ('P01', 'Por definir / N/A'), ('OTRO', 'Otro')], max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['deleted'], name='customers_c_deleted_f03073_idx'), models.Index(fields=['nombre'], name='customers_c_nombre_5f9ee9_idx'), models.Index(fields=['rfc'], name='customers_c_rfc_b70474_idx')],
            },
        ),
    ]
