# Generated by Django 5.2.7 on 2026-01-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_client_forma_pago_alter_client_regimen_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('01', '01 - Efectivo'), ('02', '02 - Cheque'), ('03', '03 - Transferencia'), ('04', '04 - Tarjetas de crédito'), ('05', '05 - Monederos electrónicos'), ('06', '06 - Dinero electrónico'), ('07', '07 - Tarjetas digitales'), ('08', '08 - Vales de despensa'), ('09', '09 - Bienes'), ('10', '10 - Servicio'), ('11', '11 - Por cuenta de tercero'), ('12', '12 - Dación en pago'), ('13', '13 - Pago por subrogación'), ('14', '14 - Pago por consignación'), ('15', '15 - Condenación'), ('16', '16 - Cancelación'), ('17', '17 - Compensación'), ('98', '98 - N/A'), ('99', '99 - Por definir')], max_length=20, null=True),
        ),
    ]
