# Generated by Django 5.2.7 on 2026-01-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_client_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pais',
            field=models.CharField(choices=[('MX', 'México'), ('US', 'Estados Unidos')], default='MX', max_length=2),
        ),
    ]
