# Generated by Django 5.2.7 on 2025-10-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_changes_alter_auditlog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('soft_delete', 'Eliminación'), ('restore', 'Restauración'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('export', 'Exportación'), ('import', 'Importación'), ('permission', 'Cambio de permisos'), ('other', 'Otra')], max_length=32),
        ),
    ]
