# Generated by Django 5.2.7 on 2025-10-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
