# Generated by Django 5.2.7 on 2025-12-08 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trucks', '0003_remove_truck_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True, verbose_name='Folio')),
                ('tipo_unidad', models.CharField(choices=[('TRUCK', 'Camión'), ('BOX', 'Caja')], max_length=10, verbose_name='Tipo de unidad')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de entrada')),
                ('fecha_salida_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha de salida estimada')),
                ('fecha_salida_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida real')),
                ('odometro_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Odómetro (km)')),
                ('descripcion_falla', models.TextField(blank=True, verbose_name='Descripción de la falla')),
                ('trabajo_solicitado', models.TextField(blank=True, verbose_name='Trabajo solicitado')),
                ('trabajo_realizado', models.TextField(blank=True, verbose_name='Trabajo realizado')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('DIAGNOSTICO', 'En diagnóstico'), ('REPARACION', 'En reparación'), ('ESPERA_REFACCION', 'En espera de refacción'), ('TERMINADA', 'Terminada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo mano de obra')),
                ('costo_refacciones', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo refacciones')),
                ('otros_costos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Otros costos')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('reefer_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_taller', to='trucks.reeferbox', verbose_name='Caja')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_taller', to='trucks.truck', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Orden de taller',
                'verbose_name_plural': 'Órdenes de taller',
                'ordering': ['-creado_en'],
            },
        ),
    ]
