# Generated by Django 5.2.7 on 2025-12-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoporder',
            name='descripcion_falla',
        ),
        migrations.RemoveField(
            model_name='workshoporder',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='workshoporder',
            name='folio',
        ),
        migrations.RemoveField(
            model_name='workshoporder',
            name='odometro_km',
        ),
        migrations.RemoveField(
            model_name='workshoporder',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='workshoporder',
            name='tipo_unidad',
        ),
        migrations.RemoveField(
            model_name='workshoporder',
            name='trabajo_realizado',
        ),
        migrations.RemoveField(
            model_name='workshoporder',
            name='trabajo_solicitado',
        ),
        migrations.AddField(
            model_name='workshoporder',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='workshoporder',
            name='notas_internas',
            field=models.TextField(blank=True, verbose_name='Notas '),
        ),
    ]
