# Generated by Django 5.2.7 on 2025-12-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_remove_workshoporder_descripcion_falla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoporder',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('REPARACION', 'En reparación'), ('ESPERA_REFACCION', 'En espera de refacción'), ('TERMINADA', 'Terminada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABIERTA', max_length=20, verbose_name='Estado'),
        ),
    ]
