# Generated by Django 5.2.7 on 2025-12-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_workshoporder_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshoporder',
            name='costo_refacciones',
        ),
    ]
