# Generated by Django 5.2.7 on 2026-01-19 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_operator_cross_border'),
        ('trucks', '0003_remove_truck_nombre'),
        ('workshop', '0004_remove_workshoporder_costo_refacciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CONVERTIDA', 'Convertida a orden de taller'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('operador', models.ForeignKey(blank=True, help_text='Operador que reporta la solicitud (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_mantenimiento', to='operators.operator', verbose_name='Operador')),
                ('orden_taller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='workshop.workshoporder', verbose_name='Orden de taller generada')),
                ('reefer_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_mantenimiento', to='trucks.reeferbox', verbose_name='Caja')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_mantenimiento', to='trucks.truck', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Solicitud de mantenimiento',
                'verbose_name_plural': 'Solicitudes de mantenimiento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
