# Generated by Django 5.2.7 on 2025-11-06 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la ubicación')),
                ('calle', models.CharField(blank=True, max_length=150)),
                ('no_ext', models.CharField(blank=True, max_length=30)),
                ('colonia', models.CharField(blank=True, max_length=120)),
                ('colonia_sat', models.CharField(blank=True, max_length=120)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(blank=True, default='México', max_length=80)),
                ('cp', models.CharField(blank=True, max_length=10)),
                ('poblacion', models.CharField(blank=True, max_length=120)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('referencias', models.TextField(blank=True, help_text='Indicaciones de acceso, referencias de calle, etc.')),
                ('horario', models.CharField(blank=True, max_length=140)),
                ('deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='customers.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['client__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('client', 'nombre'), name='uniq_location_name_per_client')],
            },
        ),
    ]
