# Generated by Django 5.2.7 on 2026-01-16 21:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Opcional: nombre comercial (ej. GDL → CDMX). Si se deja vacío, se genera en display.', max_length=150)),
                ('km_estimados', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tiempo_estimado_min', models.PositiveIntegerField(blank=True, null=True)),
                ('tarifa_cliente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto que se cobra al cliente por esta ruta (base).', max_digits=12)),
                ('casetas_estimadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Casetas estimadas (opcional, si las manejas como parte del cobro).', max_digits=12)),
                ('pago_operador', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto que se paga al operador por esta ruta (base).', max_digits=12)),
                ('bono_operador', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bono fijo opcional para el operador.', max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='customers.client', verbose_name='Cliente')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_as_destination', to='locations.location', verbose_name='Destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_as_origin', to='locations.location', verbose_name='Origen')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['client__nombre', 'origen__nombre', 'destino__nombre'],
                'constraints': [models.UniqueConstraint(fields=('client', 'origen', 'destino'), name='uniq_route_per_client_origin_dest')],
            },
        ),
    ]
