# Generated by Django 5.2.7 on 2026-01-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bono_operador',
        ),
        migrations.RemoveField(
            model_name='route',
            name='casetas_estimadas',
        ),
        migrations.RemoveField(
            model_name='route',
            name='km_estimados',
        ),
        migrations.RemoveField(
            model_name='route',
            name='tiempo_estimado_min',
        ),
    ]
