# Generated by Django 5.2.7 on 2026-01-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_route_bono_operador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='uniq_location_name_per_client',
        ),
        migrations.AlterField(
            model_name='location',
            name='pais',
            field=models.CharField(choices=[('MX', 'México'), ('US', 'Estados Unidos')], default='MX', max_length=2),
        ),
    ]
