# Generated by Django 5.2.7 on 2026-01-19 03:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='pago_transfer_propio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pago de cruce cuando el mismo operador principal cruza (operador propio).', max_digits=12),
        ),
        migrations.AddField(
            model_name='route',
            name='pago_transfer_solo_cruce',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pago de cruce cuando se asigna un operador dedicado de solo cruce.', max_digits=12),
        ),
    ]
