# Generated by Django 5.2.7 on 2025-11-12 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('operators', '0007_alter_operator_pais'),
        ('trucks', '0002_reeferbox_nombre_truck_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.CharField(choices=[('NINGUNO', 'Ninguno'), ('FULL', 'Full'), ('VACÍO', 'Vacío'), ('CRUCE', 'Cruce'), ('INTERCAMBIO', 'Intercambio')], default='NINGUNO', max_length=20, verbose_name='Tipo de transfer')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('status', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20, verbose_name='Estatus')),
                ('arrival_origin_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de llegada al origen')),
                ('departure_origin_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de salida del origen')),
                ('arrival_destination_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de llegada al destino')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_destination', to='locations.location', verbose_name='Destino')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operators.operator', verbose_name='Operador')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_origin', to='locations.location', verbose_name='Origen')),
                ('reefer_box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trucks.reeferbox')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trucks.truck', verbose_name='Camión')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-id'],
            },
        ),
    ]
