# Generated by Django 5.2.7 on 2025-11-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
