# Generated by Django 5.2.7 on 2025-12-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_ORIGEN', 'En origen'), ('EN_CURSO', 'En curso'), ('EN_DESTINO', 'En destino'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20, verbose_name='Estatus'),
        ),
    ]
