# Generated by Django 5.2.7 on 2025-12-09 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('trips', '0003_alter_trip_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaPorteCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('I', 'Ingreso'), ('T', 'Traslado')], default='T', max_length=1)),
                ('series', models.CharField(blank=True, max_length=25, null=True)),
                ('folio', models.CharField(blank=True, max_length=40, null=True)),
                ('uso_cfdi', models.CharField(default='S01', max_length=3)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('payment_form', models.CharField(default='99', max_length=2)),
                ('payment_method', models.CharField(default='PUE', max_length=3)),
                ('uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('xml_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to stamp'), ('stamped', 'Stamped'), ('canceled', 'Canceled'), ('error', 'Error')], default='draft', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, null=True)),
                ('response_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cartas_porte', to='customers.client')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carta_porte_cfdi', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Carta Porte CFDI',
                'verbose_name_plural': 'Cartas Porte CFDI',
            },
        ),
        migrations.CreateModel(
            name='CartaPorteGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienes_transp', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=255)),
                ('clave_unidad', models.CharField(max_length=5)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14)),
                ('peso_en_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('material_peligroso', models.BooleanField(default=False)),
                ('clave_material_peligroso', models.CharField(blank=True, max_length=4, null=True)),
                ('embalaje', models.CharField(blank=True, max_length=3, null=True)),
                ('carta_porte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trips.cartaportecfdi')),
            ],
        ),
        migrations.CreateModel(
            name='CartaPorteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ubicacion', models.CharField(choices=[('Origen', 'Origen'), ('Destino', 'Destino'), ('Escala', 'Escala intermedia')], max_length=10)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('num_reg_id_trib', models.CharField(blank=True, max_length=40, null=True)),
                ('residencia_fiscal', models.CharField(blank=True, max_length=3, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('pais', models.CharField(default='MEX', max_length=3)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('fecha_hora_salida_llegada', models.DateTimeField()),
                ('distancia_recorrida_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('carta_porte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.cartaportecfdi')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CartaPorteTransportFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_figura', models.CharField(choices=[('01', 'Operador'), ('02', 'Propietario'), ('03', 'Arrendatario'), ('04', 'Notificado')], max_length=2)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=255)),
                ('num_licencia', models.CharField(blank=True, max_length=40, null=True)),
                ('carta_porte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='trips.cartaportecfdi')),
            ],
        ),
    ]
