# Generated by Django 5.2.7 on 2026-01-16 21:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('locations', '0002_route'),
        ('trips', '0004_cartaportecfdi_cartaportegoods_cartaportelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bono_operador_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='casetas_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='customers.client'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pago_operador_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='locations.route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='tarifa_cliente_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
