# Generated by Django 5.2.7 on 2026-01-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_bono_operador_snapshot_trip_casetas_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='casetas_snapshot',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pago_operador_snapshot',
        ),
    ]
