# Generated by Django 5.2.7 on 2026-01-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_remove_trip_casetas_snapshot_remove_trip_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='bono_operador_snapshot',
            new_name='pago_operador_snapshot',
        ),
    ]
