# Generated by Django 5.2.7 on 2026-01-19 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_operator_cross_border'),
        ('trips', '0007_rename_bono_operador_snapshot_trip_pago_operador_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transfer_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_transfer', to='operators.operator', verbose_name='Operador de cruce (transfer)'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transfer',
            field=models.CharField(default='NINGUNO', max_length=20),
        ),
    ]
