# Generated by Django 5.2.7 on 2026-01-19 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_transfer_operator_alter_trip_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='transfer',
        ),
    ]
