# Generated by Django 5.2.7 on 2026-01-19 03:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_remove_trip_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pago_transfer_propio_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='pago_transfer_solo_cruce_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
