# Generated by Django 5.2.7 on 2026-01-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_trip_pago_transfer_propio_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='clasificacion',
            field=models.CharField(choices=[('NACIONAL', 'Nacional'), ('EXPORTACION', 'Exportación')], default='NACIONAL', max_length=20, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='trip',
            name='producto',
            field=models.CharField(blank=True, help_text='Hortaliza, Congelados, etc.)', max_length=255, verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='trip',
            name='temp_scale',
            field=models.CharField(choices=[('C', 'Celsius (°C)'), ('F', 'Fahrenheit (°F)')], default='C', max_length=1, verbose_name='Escala de temperatura'),
        ),
        migrations.AddField(
            model_name='trip',
            name='temperatura_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura máxima'),
        ),
        migrations.AddField(
            model_name='trip',
            name='temperatura_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temperatura mínima'),
        ),
    ]
