# Generated by Django 5.2.7 on 2026-01-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_trip_clasificacion_trip_producto_trip_temp_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='temp_scale',
            field=models.CharField(choices=[('F', 'Fahrenheit (°F)'), ('C', 'Celsius (°C)')], default='C', max_length=1, verbose_name='Escala de temperatura'),
        ),
    ]
