# Generated by Django 5.2.7 on 2026-01-29 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('trips', '0012_alter_trip_temp_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaportegoods',
            name='mercancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carta_porte_goods', to='goods.mercancia'),
        ),
    ]
