# Generated by Django 5.2.7 on 2026-02-03 23:42

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_cartaportegoods_mercancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaportecfdi',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='itrn_us_entry',
            field=models.CharField(blank=True, max_length=80, verbose_name='ITRN US entry'),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='orden',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='pedimento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='retencion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
