# Generated by Django 5.2.7 on 2026-02-04 00:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_cartaportecfdi_fecha_cartaportecfdi_itrn_us_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaportegoods',
            name='bienes_transp',
        ),
        migrations.RemoveField(
            model_name='cartaportegoods',
            name='clave_material_peligroso',
        ),
        migrations.RemoveField(
            model_name='cartaportegoods',
            name='clave_unidad',
        ),
        migrations.RemoveField(
            model_name='cartaportegoods',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cartaportegoods',
            name='material_peligroso',
        ),
        migrations.AddField(
            model_name='cartaportegoods',
            name='moneda',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cartaportegoods',
            name='pedimento',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cartaportegoods',
            name='valor_mercancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='cartaportegoods',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='cartaportegoods',
            name='embalaje',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
