# Generated by Django 5.2.7 on 2026-02-04 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_remove_cartaportegoods_bienes_transp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaportecfdi',
            old_name='fecha',
            new_name='fecha_llegada',
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='fecha_salida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
