# Generated by Django 5.2.7 on 2026-02-04 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_rename_fecha_cartaportecfdi_fecha_llegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaportecfdi',
            name='fecha_llegada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cartaportecfdi',
            name='fecha_salida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
