# Generated by Django 5.2.7 on 2026-02-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_alter_cartaportecfdi_fecha_llegada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaportecfdi',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
