# Generated by Django 5.2.7 on 2026-02-04 07:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_cartaportecfdi_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaportetransportfigure',
            name='carta_porte',
        ),
        migrations.CreateModel(
            name='CartaPorteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=14)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('producto', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('iva_pct', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=6)),
                ('ret_iva_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('iva_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ret_iva_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('importe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('carta_porte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.cartaportecfdi')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='CartaPorteLocation',
        ),
        migrations.DeleteModel(
            name='CartaPorteTransportFigure',
        ),
    ]
