# Generated by Django 5.2.7 on 2026-02-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_remove_cartaportetransportfigure_carta_porte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaPorteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ubicacion', models.CharField(choices=[('Origen', 'Origen'), ('Destino', 'Destino'), ('Escala', 'Escala intermedia')], max_length=10)),
                ('rfc', models.CharField(max_length=13)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('num_reg_id_trib', models.CharField(blank=True, max_length=40, null=True)),
                ('residencia_fiscal', models.CharField(blank=True, max_length=3, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=20, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('pais', models.CharField(default='MEX', max_length=3)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('fecha_hora_salida_llegada', models.DateTimeField()),
                ('distancia_recorrida_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('carta_porte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.cartaportecfdi')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
