# Generated by Django 5.2.7 on 2026-02-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_cartaportelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaportelocation',
            name='fecha_hora_salida_llegada',
        ),
    ]
