# Generated by Django 5.2.7 on 2026-02-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_remove_cartaportelocation_fecha_hora_salida_llegada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='observations',
        ),
    ]
