# Generated by Django 5.2.7 on 2026-02-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_remove_trip_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaportecfdi',
            name='itrn_us_entry',
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='factura_clinte',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='itrn',
            field=models.CharField(blank=True, max_length=80, verbose_name='ITRN'),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='us_entry',
            field=models.CharField(blank=True, max_length=80, verbose_name='US entry'),
        ),
        migrations.AlterField(
            model_name='cartaportecfdi',
            name='type',
            field=models.CharField(choices=[('I', 'Ingreso'), ('T', 'Traslado')], default='I', max_length=1),
        ),
    ]
