# Generated by Django 5.2.7 on 2026-02-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_remove_cartaportecfdi_itrn_us_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaportegoods',
            name='comercio_exterior_uuid',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
