# Generated by Django 5.2.7 on 2026-02-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0024_cartaportegoods_comercio_exterior_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaportecfdi',
            name='emitter_no_cert',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cartaportecfdi',
            name='sat_no_cert',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
